name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --no-git-checks --provenance
