name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run tests
        run: pnpm test
